import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { ESLint, type Linter } from 'eslint';
import { afterAll, describe, expect, it } from 'vitest';
import { mobile, web, type ExtraLayer } from './index.ts';

const dirs: string[] = [];

async function lint(config: Linter.Config[], files: Record<string, string>): Promise<Record<string, string[]>> {
  const cwd = mkdtempSync(join(tmpdir(), 'lupira-eslint-'));
  dirs.push(cwd);
  for (const [path, source] of Object.entries(files)) {
    mkdirSync(dirname(join(cwd, path)), { recursive: true });
    writeFileSync(join(cwd, path), source);
  }
  const results = await new ESLint({ cwd, overrideConfigFile: true, overrideConfig: config }).lintFiles(['src/**/*.{ts,tsx}']);
  return Object.fromEntries(
    results.map((r) => [r.filePath.slice(cwd.length + 1), r.messages.filter((m) => m.ruleId?.startsWith('boundaries/') || m.ruleId === 'no-restricted-imports').map((m) => m.ruleId!)]),
  );
}

afterAll(() => {
  for (const d of dirs) rmSync(d, { recursive: true, force: true });
});

const leaf = 'export const x = 1;\n';
const stack = {
  'src/domain/leaf.ts': leaf,
  'src/data/leaf.ts': leaf,
  'src/sync/leaf.ts': leaf,
  'src/state/leaf.ts': leaf,
  'src/ui/leaf.ts': leaf,
  'src/config/leaf.ts': leaf,
  'src/collector/leaf.ts': leaf,
  'src/data/api/generated/leaf.ts': leaf,
};

describe('mobile()', () => {
  const collector: ExtraLayer = { name: 'collector', pattern: 'src/collector/**', imports: ['data', 'domain'], importedBy: ['state', 'ui'] };

  it('allows downward imports, externals and the platform packages at their layers', async () => {
    const result = await lint(mobile({ layers: [collector] }), {
      ...stack,
      'src/data/a.ts': "import '../domain/leaf';\nimport '../config/leaf';\nimport react from 'react';\nimport '@danbro96/lupira-http/transport';\nimport '@danbro96/lupira-expo-oidc/tokenSession';\nimport '@danbro96/lupira-expo-sqlite/expoDb';\nimport '@danbro96/lupira-sync-core/lww';\nexport { react };\n",
      'src/domain/a.ts': "import '@danbro96/lupira-http/apiError';\nimport '@danbro96/lupira-domain-core/ids';\n",
      'src/ui/a.tsx': "import '../state/leaf';\nimport '../collector/leaf';\nimport '@danbro96/lupira-expo-paper/Button';\nimport '@danbro96/lupira-tokens-core/color';\n",
      'src/collector/a.ts': "import '../data/leaf';\nimport '../domain/leaf';\nimport '@danbro96/lupira-expo-oidc/oidc';\n",
      'src/data/a.test.ts': "import '@danbro96/lupira-expo-sqlite/node';\n",
      'src/sync/a.ts': "import '@danbro96/lupira-sync-engine/engine';\nimport '@danbro96/lupira-sync-engine/expo/triggers';\nimport '@danbro96/lupira-expo-query/invalidateOnChange';\n",
      'src/state/a.ts': "import '@danbro96/lupira-sync-engine/bannerState';\nimport '@danbro96/lupira-expo-query/mirrorQuery';\n",
      'src/ui/b.tsx': "import '@danbro96/lupira-sync-engine/expo/triggers';\nimport '@danbro96/lupira-expo-query/online';\n",
    });
    expect(Object.entries(result).filter(([, v]) => v.length)).toEqual([]);
  });

  it.each([
    ['domain imports data', 'src/domain/bad.ts', "import '../data/leaf';"],
    ['data imports sync', 'src/data/bad.ts', "import '../sync/leaf';"],
    ['sync imports state', 'src/sync/bad.ts', "import '../state/leaf';"],
    ['state imports ui', 'src/state/bad.ts', "import '../ui/leaf';"],
    ['collector imports ui', 'src/collector/bad.ts', "import '../ui/leaf';"],
    ['collector imports sync', 'src/collector/bad.ts', "import '../sync/leaf';"],
    ['config imports data', 'src/config/bad.ts', "import '../data/leaf';"],
    ['domain imports generated by default', 'src/domain/bad.ts', "import '../data/api/generated/leaf';"],
    ['data imports the paper kit', 'src/data/bad.ts', "import '@danbro96/lupira-expo-paper/Button';"],
    ['domain imports the oidc client', 'src/domain/bad.ts', "import '@danbro96/lupira-expo-oidc/oidc';"],
    ['an unknown platform package', 'src/ui/bad.tsx', "import '@danbro96/lupira-nonexistent';"],
    ['data imports the sync engine', 'src/data/bad.ts', "import '@danbro96/lupira-sync-engine/engine';"],
    ['domain imports the sync engine', 'src/domain/bad.ts', "import '@danbro96/lupira-sync-engine/types';"],
    ['data imports the query kit', 'src/data/bad.ts', "import '@danbro96/lupira-expo-query/mirrorQuery';"],
    ['domain imports the query kit', 'src/domain/bad.ts', "import '@danbro96/lupira-expo-query/queryClient';"],
    ['production code imports the node test double', 'src/data/bad.ts', "import '@danbro96/lupira-expo-sqlite/node';"],
  ])('rejects: %s', async (_name, path, source) => {
    const result = await lint(mobile({ layers: [collector] }), { ...stack, [path]: `${source}\n` });
    expect(result[path]!.length).toBeGreaterThan(0);
  });

  it('lets domain import the generated types only on request', async () => {
    const files = { ...stack, 'src/domain/a.ts': "import '../data/api/generated/leaf';\n" };
    expect((await lint(mobile({ domainImportsGenerated: true }), files))['src/domain/a.ts']).toEqual([]);
  });
});

describe('web()', () => {
  const files = {
    'src/domain/leaf.ts': leaf,
    'src/data/leaf.ts': leaf,
    'src/state/leaf.ts': leaf,
    'src/ui/leaf.ts': leaf,
    'src/config/leaf.ts': leaf,
  };

  it('allows downward imports and the platform packages at their layers', async () => {
    const result = await lint(web({ domain: true }), {
      ...files,
      'src/data/a.ts': "import '../domain/leaf';\nimport '@danbro96/lupira-http/transport';\nimport '@danbro96/lupira-web-session/cookieTransport';\n",
      'src/state/a.ts': "import '../data/leaf';\nimport '@danbro96/lupira-web-session/useSession';\n",
      'src/ui/a.tsx': "import '../state/leaf';\nimport '@danbro96/lupira-web-mui/theme';\nimport '@danbro96/lupira-tokens-core/color';\n",
    });
    expect(Object.entries(result).filter(([, v]) => v.length)).toEqual([]);
  });

  it.each([
    ['data imports state', 'src/data/bad.ts', "import '../state/leaf';"],
    ['state imports ui', 'src/state/bad.ts', "import '../ui/leaf';"],
    ['data imports the web kit', 'src/data/bad.ts', "import '@danbro96/lupira-web-mui/theme';"],
    ['data imports useSession', 'src/data/bad.ts', "import '@danbro96/lupira-web-session/useSession';"],
    ['an unknown platform package', 'src/ui/bad.tsx', "import '@danbro96/lupira-nonexistent';"],
  ])('rejects: %s', async (_name, path, source) => {
    const result = await lint(web({ domain: true }), { ...files, [path]: `${source}\n` });
    expect(result[path]!.length).toBeGreaterThan(0);
  });
});
