<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.0</Version>
    <Description>On-demand, idempotent time-range Postgres partitions (weekly/monthly) with retention drop.</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Lupira.Postgres.Partitions.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.4" />
  </ItemGroup>

</Project>
