/**
 * Concept names, not glyphs — this package stays dependency-free, so it cannot hold components.
 * Each surface resolves these through its own `ui/icons.ts`: web to `@mui/icons-material`,
 * mobile to `MaterialIcons`. Typing a resolver as `Record<IconName, …>` makes a name added here
 * fail its build until it is mapped.
 */
export const ICON_NAMES = [
  'account',
  'add',
  'alert',
  'cake',
  'calendar',
  'celebration',
  'check',
  'checkBox',
  'checkCircle',
  'chevronLeft',
  'chevronRight',
  'cleaning',
  'clear',
  'close',
  'contacts',
  'delete',
  'email',
  'event',
  'expand',
  'filter',
  'group',
  'heading',
  'hotel',
  'inbox',
  'layers',
  'link',
  'locate',
  'locateFixed',
  'locationOff',
  'lock',
  'luggage',
  'map',
  'medical',
  'menu',
  'more',
  'person',
  'photos',
  'place',
  'restaurant',
  'robot',
  'run',
  'schedule',
  'search',
  'settings',
  'star',
  'starOutline',
  'target',
  'tools',
  'tune',
  'walk',
] as const;

export type IconName = (typeof ICON_NAMES)[number];
